### ISSUE TITLE
mix compile failed.

### ISSUE THREAD

**Issue by efrainmunoz** [mischov/meeseeks_html5ever#26]
==> meeseeks_html5ever
Compiling NIF crate :meeseeks_html5ever_nif (native/meeseeks_html5ever_nif)...
could not compile dependency :meeseeks_html5ever, "mix compile" failed. You can recompile 
this dependency with "mix deps.compile meeseeks_html5ever", update it with "mix deps.updat
e meeseeks_html5ever" or clean it with "mix deps.clean meeseeks_html5ever"
** (ErlangError) Erlang error: :enoent
    (elixir) lib/system.ex:791: System.cmd("cargo", ["rustc", "--no-default-features", "--
release"], [cd: "/home/ubuntu/sg3-portal/deps/meeseeks_html5ever/native/meeseeks_html5ever
_nif", stderr_to_stdout: true, env: [{"CARGO_TARGET_DIR", "/home/ubuntu/sg3-portal/_build/
dev/rustler_crates/meeseeks_html5ever_nif"}], into: %IO.Stream{device: :standard_io, line_
or_bytes: :line, raw: false}])
    lib/mix/tasks/compile.rustler.ex:51: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/tasks/compile.rustler.ex:14: Mix.Tasks.Compile.Rustler.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:73: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:53: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:24: anonymous fn/1 in Mix.Tasks.Compile.All.run/1

Im using Erlang/OTP 21 [erts-10.0], Elixir (1.6.6)

**Comment by mischov** [comment]
Do you have Rust installed?

**Comment by efrainmunoz** [comment]
rustup 1.18.3
cargo 1.37.0
rustc 1.37.0

**Comment by mischov** [comment]
And you've tried cleaning out and recompiling all your deps?

That combination of Elixir and Erlang [is one we test](https://github.com/mischov/meeseeks_html5ever/blob/a19a6ba008369dcf0f93d4095a2558c409be17fd/.travis.yml#L13-L14) so it should be working. I'll try to recreate the problem later.

Is this your first time trying to use Meeseeks or was it working before and it just started failing? Anything else I should know when trying to recreate?

**Comment by efrainmunoz** [comment]
Yes I tried cleaning and recompilling all my deps several times but nothing. Its running on other server running the same OS (Ubuntu-18.04 LTS) without problems. Trying to install it on a new server with the same OS. Im also using ASDF as my runtime version manager. Thanks for taking the time.

**Comment by mischov** [comment]
Ah, is cargo on path?

**Comment by efrainmunoz** [comment]
$ cargo -V
cargo 1.37.0 (9edd08916 2019-08-02)

**Comment by mischov** [comment]
That's odd. It's like [this](https://github.com/mischov/meeseeks/issues/41) which was absence of Rust so trying to figure out if there's some reason it can't find Rust or Cargo.

**Comment by efrainmunoz** [comment]
Yeah. And I just created a hello_world project using cargo, built, and ran it..

**Comment by efrainmunoz** [comment]
Solved. Didn't have the right permissions to the directory so I was trying to run "sudo mix deps.compile --all". Once I had the ability to run mix without sudo everything went fine.

**Comment by mischov** [comment]
Ah! Thanks for reporting back, it's good to know that can cause it.

New servers are such a pain. :)

**Comment by efrainmunoz** [comment]
Sure. And thanks again.
