### ISSUE TITLE
compilation failed with elixir 1.8.1-otp-21 & erlang 22.3.4.26

### ISSUE THREAD

**Issue by tomwang57** [mischov/meeseeks_html5ever#65]
**error message**:

-----------------------------
==> meeseeks_html5ever
Compiling NIF crate :meeseeks_html5ever_nif (native/meeseeks_html5ever_nif)...
   Compiling markup5ever v0.7.5
   Compiling erlang_nif-sys v0.6.4
   Compiling rustler v0.20.0
error: failed to run custom build command for `erlang_nif-sys v0.6.4`

Caused by:
  process didn't exit successfully: `/Users/57block/work/messages/_build/dev/rustler_crates/meeseeks_html5ever_nif/release/build/erlang_nif-sys-652fa8f99a73d793/build-script-build` (exit status: 101)
  --- stdout
  Unsupported Erlang version.

  Is the erlang_nif-sys version up to date in the Cargo.toml?
  Does 'cargo update' fix it?
  If not please report at https://github.com/goertzenator/erlang_nif-sys.

  --- stderr
  thread 'main' panicked at 'gen_api.erl encountered an error.', /Users/57block/.cargo/registry/src/index.crates.io-6f17d22bba15001f/erlang_nif-sys-0.6.4/build.rs:28:22
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `rustler v0.20.0`

Caused by:
  process didn't exit successfully: `/Users/57block/work/messages/_build/dev/rustler_crates/meeseeks_html5ever_nif/release/build/rustler-6cf301e09488846d/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Erlang version 2.15 not handled, please file a a bug report.', /Users/57block/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustler-0.20.0/build.rs:51:10
-----------------

rustc 1.72.1

I tried `cargo update` in the nif folder and i did't help as well.

**Comment by mischov** [comment]
It appears to me that you're probably using an pretty old version of Meeseeks/Meeseeks_Html5ever, as well as old version of Elixir and Erlang.

Meeseeks_Html5ever requires a minimum combination of Elixir 1.12.0 and Erlang/OTP 23.0, so you're behind on both of those, not to mention that you're for some reason trying to combine `elixir 1.8.1-otp-21` with `erlang 22.3.4.26` (ie, otp-22).

I'm sorry but I can't help you solve this problem unless you're using supported versions of everything.
